# Generated by Django 2.0.9 on 2018-11-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='sitioweb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
