# Generated by Django 2.0.9 on 2018-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181108_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
