# Generated by Django 2.1.2 on 2018-10-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181028_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='estado',
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Estado'),
            preserve_default=False,
        ),
    ]
