# Generated by Django 2.1.2 on 2018-10-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181028_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='estado',
        ),
        migrations.AlterField(
            model_name='negocio',
            name='municipio',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
