# Generated by Django 2.0.9 on 2018-10-26 05:21

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ubicacion_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='address',
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='ubicacion',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
