# Generated by Django 2.0.9 on 2018-10-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ubicacion_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicacion', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='latitud',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='longitud',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
