# Generated by Django 2.0.9 on 2018-10-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181026_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='ubicacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Ubicacion'),
            preserve_default=False,
        ),
    ]
