# Generated by Django 2.0.9 on 2018-10-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181026_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='pais',
        ),
    ]
