# Generated by Django 2.0.9 on 2018-10-26 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181026_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negocio',
            old_name='fechaNacimientotitular',
            new_name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='estado',
        ),
        migrations.AddField(
            model_name='negocio',
            name='correo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negocio',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='nombreTitular',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negocio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pais'),
        ),
    ]
