# Generated by Django 2.0.9 on 2018-10-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181026_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='negocio',
            name='Pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Pais'),
            preserve_default=False,
        ),
    ]
