# Generated by Django 2.0.9 on 2018-10-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181026_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negocio',
            old_name='Pais',
            new_name='pais',
        ),
    ]
