# Generated by Django 2.0.9 on 2018-10-27 00:36

from django.db import migrations, models
import django.db.models.deletion
# from ..models import *


class Migration(migrations.Migration):
    # ubicacion = Ubicacion.objects.first()
    dependencies = [
        ('app', '0013_auto_20181026_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ubicacion'),
            preserve_default=False,
        ),
    ]
